/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "pulse": [],
    "sanctum.csrf-cookie": [],
    "default-livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "wallets.index": [],
    "wallets.create": [],
    "wallets.store": [],
    "wallets.show": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.edit": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.update": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.destroy": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.index": [],
    "portfolios.create": [],
    "portfolios.store": [],
    "portfolios.show": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.edit": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.update": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.destroy": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
